# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v0

      # Runs a set of commands using the runners shell
      - name: Run all tests
        uses: matlab-actions/run-command@v0
        with:
          command: runAllTests
          
      - name: Upload Artifacts  
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: artifacts/   

      - name: Create public index
        run: |
          echo '<!DOCTYPE html>' >> public/index.html
          echo '<html>' >> public/index.html
          echo '  <head>' >> public/index.html
          echo '    <title>Job Results</title>' >> public/index.html
          echo '  </head>' >> public/index.html
          echo '  <body>' >> public/index.html
          echo '    <a href="test-results/index.html">Test Results</a>' >> public/index.html
          echo '    <a href="code-coverage/index.html">Code Coverage</a>' >> public/index.html
          echo '  </body>' >> public/index.html
          echo '</html>' >> public/index.html
        
      - name: Publish Results ðŸš€
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: public # The folder the action should deploy.
          CLEAN: true # 
      
 
          
#      - name: XUnit Viewer
 #       uses: AutoModality/action-xunit-viewer@v1.0.1
  #      with:
   #       results: artifacts/testResults.xml
